export const countries = [
    {
        id: "1",
        drapeau: "https://flagcdn.com/w320/af.png",
        langues: { eng: "Pashto, Dari" },
        nom: "Afghanistan",
        continent: "Asia",
        region: "South Asia",
        capital: ["Kabul"],
        demarrageSemaine: "Saturday",
        status: true,
        population: "39000000",
        superficie: "652230"
    },
    {
        id: "2",
        drapeau: "https://flagcdn.com/w320/al.png",
        langues: { eng: "Albanian" },
        nom: "Albania",
        continent: "Europe",
        region: "Balkans",
        capital: ["Tirana"],
        demarrageSemaine: "Sunday",
        status: true,
        population: "2800000",
        superficie: "28748"
    },
    {
        id: "3",
        drapeau: "https://flagcdn.com/w320/dz.png",
        langues: { eng: "Arabic, Berber" },
        nom: "Algeria",
        continent: "Africa",
        region: "North Africa",
        capital: ["Algiers"],
        demarrageSemaine: "Saturday",
        status: true,
        population: "44000000",
        superficie: "2381741"
    },
    {
        id: "4",
        drapeau: "https://flagcdn.com/w320/ar.png",
        langues: { eng: "Spanish" },
        nom: "Argentina",
        continent: "South America",
        region: "South America",
        capital: ["Buenos Aires"],
        demarrageSemaine: "Sunday",
        status: true,
        population: "45000000",
        superficie: "2780400"
    },
    {
        id: "5",
        drapeau: "https://flagcdn.com/w320/am.png",
        langues: { eng: "Armenian" },
        nom: "Armenia",
        continent: "Asia",
        region: "Caucasus",
        capital: ["Yerevan"],
        demarrageSemaine: "Sunday",
        status: true,
        population: "3000000",
        superficie: "29743"
    },
    {
        id: "6",
        drapeau: "https://flagcdn.com/w320/au.png",
        langues: { eng: "English" },
        nom: "Australia",
        continent: "Oceania",
        region: "Australia",
        capital: ["Canberra"],
        demarrageSemaine: "Sunday",
        status: true,
        population: "25000000",
        superficie: "7692024"
    },
    {
        id: "7",
        drapeau: "https://flagcdn.com/w320/be.png",
        langues: { eng: "Dutch, French, German" },
        nom: "Belgium",
        continent: "Europe",
        region: "Western Europe",
        capital: ["Brussels"],
        demarrageSemaine: "Sunday",
        status: true,
        population: "11000000",
        superficie: "30528"
    },
    {
        id: "8",
        drapeau: "https://flagcdn.com/w320/br.png",
        langues: { eng: "Portuguese" },
        nom: "Brazil",
        continent: "South America",
        region: "South America",
        capital: ["Brasília"],
        demarrageSemaine: "Sunday",
        status: true,
        population: "213000000",
        superficie: "8515767"
    },
    {
        id: "9",
        drapeau: "https://flagcdn.com/w320/ca.png",
        langues: { eng: "English, French" },
        nom: "Canada",
        continent: "North America",
        region: "North America",
        capital: ["Ottawa"],
        demarrageSemaine: "Sunday",
        status: true,
        population: "38000000",
        superficie: "9984670"
    },
    {
        id: "10",
        drapeau: "https://flagcdn.com/w320/cl.png",
        langues: { eng: "Spanish" },
        nom: "Chile",
        continent: "South America",
        region: "South America",
        capital: ["Santiago"],
        demarrageSemaine: "Sunday",
        status: true,
        population: "19000000",
        superficie: "756102"
    },
    {
        id: "11",
        drapeau: "https://flagcdn.com/w320/cn.png",
        langues: { eng: "Mandarin" },
        nom: "China",
        continent: "Asia",
        region: "East Asia",
        capital: ["Beijing"],
        demarrageSemaine: "Monday",
        status: true,
        population: "1400000000",
        superficie: "9596961"
    },
    {
        id: "12",
        drapeau: "https://flagcdn.com/w320/co.png",
        langues: { eng: "Spanish" },
        nom: "Colombia",
        continent: "South America",
        region: "South America",
        capital: ["Bogotá"],
        demarrageSemaine: "Sunday",
        status: true,
        population: "51000000",
        superficie: "1141748"
    },
    {
        id: "13",
        drapeau: "https://flagcdn.com/w320/cr.png",
        langues: { eng: "Spanish" },
        nom: "Costa Rica",
        continent: "North America",
        region: "Central America",
        capital: ["San José"],
        demarrageSemaine: "Monday",
        status: true,
        population: "5000000",
        superficie: "51100"
    },
    {
        id: "14",
        drapeau: "https://flagcdn.com/w320/cz.png",
        langues: { eng: "Czech" },
        nom: "Czech Republic",
        continent: "Europe",
        region: "Central Europe",
        capital: ["Prague"],
        demarrageSemaine: "Monday",
        status: true,
        population: "10700000",
        superficie: "78865"
    },
    {
        id: "15",
        drapeau: "https://flagcdn.com/w320/dk.png",
        langues: { eng: "Danish" },
        nom: "Denmark",
        continent: "Europe",
        region: "Northern Europe",
        capital: ["Copenhagen"],
        demarrageSemaine: "Monday",
        status: true,
        population: "5800000",
        superficie: "43094"
    },
    {
        id: "16",
        drapeau: "https://flagcdn.com/w320/eg.png",
        langues: { eng: "Arabic" },
        nom: "Egypt",
        continent: "Africa",
        region: "North Africa",
        capital: ["Cairo"],
        demarrageSemaine: "Saturday",
        status: true,
        population: "100000000",
        superficie: "1002450"
    },
    {
        id: "17",
        drapeau: "https://flagcdn.com/w320/fr.png",
        langues: { eng: "French" },
        nom: "France",
        continent: "Europe",
        region: "Western Europe",
        capital: ["Paris"],
        demarrageSemaine: "Monday",
        status: true,
        population: "67000000",
        superficie: "551695"
    },
    {
        id: "18",
        drapeau: "https://flagcdn.com/w320/de.png",
        langues: { eng: "German" },
        nom: "Germany",
        continent: "Europe",
        region: "Central Europe",
        capital: ["Berlin"],
        demarrageSemaine: "Monday",
        status: true,
        population: "83000000",
        superficie: "357022"
    },
    {
        id: "19",
        drapeau: "https://flagcdn.com/w320/in.png",
        langues: { eng: "Hindi, English" },
        nom: "India",
        continent: "Asia",
        region: "South Asia",
        capital: ["New Delhi"],
        demarrageSemaine: "Monday",
        status: true,
        population: "1380004385",
        superficie: "3287263"
    },
    {
        id: "20",
        drapeau: "https://flagcdn.com/w320/it.png",
        langues: { eng: "Italian" },
        nom: "Italy",
        continent: "Europe",
        region: "Southern Europe",
        capital: ["Rome"],
        demarrageSemaine: "Monday",
        status: true,
        population: "60000000",
        superficie: "301340"
    }
];
